### ISSUE TITLE
Toggle text should be consistent across browsers

### ISSUE THREAD

**Issue by dengeist** [pearson-ux/web-components#159]
In some environments, the internal on/off labels of the toggle component are not quite vertically aligned in Chrome on MacOS. The text appears to be a different thickness in each the Big Three as well.

![image](https://user-images.githubusercontent.com/13525251/47966985-1f5a2c00-e00d-11e8-81b1-4d377253da23.png)

However, this does not appear to be easily reproduced. Tested environments:
- OS: MacOS 10.14
- **Safari:** 12.0
- **Firefox:** 63.0
- **Chrome:** 70.0.

Help wanted to reproduce this issue. If it cannot be reproduced in recent versions of MacOS or leading browsers, it can be closed.

Thanks to @annehong for identifying this issue and providing screenshots.

**Comment by davodey** [comment]
@dengeist @annehong is this a PL issue or Web Component issue?  I have a feeling this code lives in patternlab and is not part of WC.  I have not updated PL to use the WC toggle yet.  

If it is a PL issue, lets move this over to the pearson-pattern-lab repo or to the repo where the PL lives.

**Comment by annehong** [comment]
I thought you created a ticket so that what is in PL gets translated to WC. 

The glp-pl uses a teal toggle, and WS uses a green toggle, but the code issues are the same -- misalignment of the text depending on browser how browser renders the font. I copied and pasted the code from glp-pl for WS. I was trying to fix this in WS, and noticed that @dengeist added the toggle to WC so I wanted to share the issue I was having with toggle.

**Comment by davodey** [comment]
@annehong we usually start with the code that's in patternlab if its available, but rarely does it ever get translated 100%.  

I get what you're saying though.  @dengeist it looks like the issue is being caused by a line-height property on :host.  If we remove this, the problem seems to fix itself.

![screen shot 2018-11-08 at 8 30 07 am](https://user-images.githubusercontent.com/5407196/48208674-93a80e80-e330-11e8-8a06-076caffe1328.png)

**Comment by dengeist** [comment]
Good find, @davodey. That line-height was from an old spec where the whole pill shape was taller.

**Comment by annehong** [comment]
@davodey 
Um, I think I tried removing the line-height in WS, which did fix it at my 100% zoom, but when you zoom up, it looks misaligned. For some reason the zoom @+1 is what Hop sees on his monitor.

Here is a screenshot:
<img width="1182" alt="screen shot 2018-11-10 at 6 34 36 pm" src="https://user-images.githubusercontent.com/9653426/48308356-9153d900-e517-11e8-818b-e5fd09b60df0.png">
