### ISSUE TITLE
Date Picker HTML, CSS, JS

### ISSUE THREAD

**Issue by davodey** [pearson-ux/web-components#18]
Use the markup kit to build out date picker with accessible markup and behavior, styled to UXF specification.

Markup kit:
https://github.com/pearson-ux/web-component-markup-kit

Framework specification
https://uxframework.pearson.com/c/date-picker
https://uxframework.pearson.com/c/calendar

**Comment by jackiejakob** [comment]
Link from Anne/Paul on accessible reference: https://datepicker.now.sh/

**Comment by antelopeb** [comment]
Blocked until the calendar is complete.

**Comment by pauljadam** [comment]
@sarahvc  I do recommend the HTML5 input type=date native control for accessibility. Not all desktop browsers support it yet like Safari but on mobile the support is good and provides the native calendar entry controls that they already use in the OS. You get the accessibility for free with the native date picker. Could also use a Polyfill like the WET Input type="date" polyfill (date picker), https://wet-boew.github.io/wet-boew/demos/datepicker/datepicker-en.html, so that browsers like Chrome and Safari iOS get the native date picker but browser like Safari macOS get the custom date picker. WET's custom date picker is accessible, just coded differently than the other example linked.

**Comment by sarahvc** [comment]
Hi @davodey , are you going to take over this one?

**Comment by davodey** [comment]
@sarahvc how busy are you?  I don't want to take you away from the priorities discussed last Wed.  Since it's essentially a clone of the time picker with a different icon and popup, I have no problem doing it.

**Comment by sarahvc** [comment]
@davodey I'll leave it for you then. Thank you! Honestly I'm not too busy to take this, but I do have a few different projects at the same time and it costs me to switch my mind set between them.
