### ISSUE TITLE
Footer Component

### ISSUE THREAD

**Issue by davodey** [pearson-ux/web-components#23]
Convert the existing footer markup into a fully functioning web component using the spec kit:

Spec Kit:
https://github.com/pearson-ux/web-component-spec-kit

**Comment by sarahvc** [comment]
@davodey @dengeist Hi I wonder what's the status of this footer component? Should I continue working on this since I added the html/css?

**Comment by dengeist** [comment]
@sarahvc Now that the Footer markup is merged, you're free to continue with the Footer web component. Note that the way a component is made has changed since you began work on the footer. Refer to the [Spec Kit](https://github.com/pearson-ux/web-component-spec-kit/blob/master/js/main.js) to see how components should be structured. We _no longer_ create HTML imports. 

Message me if you have questions!

**Comment by sarahvc** [comment]
@davodey I think this is done. My work has been merged. https://github.com/pearson-ux/web-components/pull/163.

**Comment by davodey** [comment]
@sarahvc nice!
