### ISSUE TITLE
Time Picker HTML, CSS, JS

### ISSUE THREAD

**Issue by davodey** [pearson-ux/web-components#32]
Use the markup kit to build out time picker with accessible markup and behavior, styled to UXF specification.

Markup kit:
https://github.com/pearson-ux/web-component-markup-kit

Framework specification
https://uxframework.pearson.com/c/time-picker

**Comment by pauljadam** [comment]
@davodey Should this not be coded as a Native HTML input=time element rather than a custom control? That gives you the keyboard and screen reader accessibility for free, you just can't style it same as a <select> cannot be styled. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

I recommend doing native controls over the custom controls for the keyboard and screen reader accessibility support.

Could also possibly offer both options, native time picker and custom time picker.

**Comment by dengeist** [comment]
I agree with Paul. My only issue is that Pearson has a track record of not wanting to use these native widgets. It might be best to do what Paul suggests and offer both, if that's in scope for this release.

**Comment by davodey** [comment]
@pauljadam @dengeist I agree.  My only concern is time.  Let's do both, but add the native widget in our second release. How does that sound?

**Comment by davodey** [comment]
@jackiejakob I notice in IE11 the popup doesn't show when the input is clicked.

**Comment by pauljadam** [comment]
@davodey sounds good! I'd like to see both options offered for these HTML5 input types like date also.

**Comment by davodey** [comment]
@pauljadam Yeah, you got it!
