### ISSUE TITLE
UK - Header anchor href is not configurable 

### ISSUE THREAD

**Issue by walkyv** [pearson-ux/web-components#360]
The gravity header component  holds the Pearson logo which is wrapped by an anchor tag, which is clickable and points to "https://console.pearson.com/console/home"

Could the anchor tags href attribute be configurable by the addition of an optional logo-href attribute?  So if the attribute is missing then the anchor tag is removed, and if the attribute is set then the anchor's href is set to this value. 

![Header](https://user-images.githubusercontent.com/47328314/72993413-40af5f80-3ded-11ea-9f98-5812bfed767a.png)

**Comment by davodey** [comment]
@walkyv this issue is resolved.  The updated header has been released, by default we no longer add a link in the logo.  To enable this you'll need to add an attribute of 'logolink' with the value being a valued URL.  The logo will then point to that.  If no attribute is present, links will be disabled.

documentation:
https://ux.pearson.com/web-components/docs/web-components/header
