### ISSUE TITLE
UK - Table add column sort functionality

### ISSUE THREAD

**Issue by walkyv** [pearson-ux/web-components#372]
It would be really great if column sort functionality could be added to the table component.

**Comment by davodey** [comment]
@walkyv unfortunately, due to the complexity of tables, we're going to leave that to devs.  Tables are hard to make shareable due to the markup and complex structure of table elements.

HOWEVER... who says we have to use tables right?  Maybe see if design can put something together that gives you what you want, but isn't necessary a table?  Does that make sense?

**Comment by walkyv** [comment]
Thanks David
